### ISSUE TITLE
HBDetail.js 无法在QX下运行

### ISSUE THREAD

**Issue by EchoChan314** [Aerozb/JD_HongBaoDetails#1]
原因: ReferenceError: Can't find variable: process!

**Comment by Aerozb** [comment]
我没有圈X，都是node环境下使用，我按照LXK大佬添加了两个圈X文件，这个订阅地址看看行不行，看看还有啥报错
https://raw.githubusercontent.com/Aerozb/JD_HongBaoDetails/main/QuantumultX/Aerozb_gallery.json

**Comment by Aerozb** [comment]
更新了，你看看能不能，设置通知详情等级

**Comment by EchoChan314** [comment]
> 更新了，你看看能不能，设置通知详情等级

可以的。
